services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555" # Mapeando a porta para o Prisma Studio
    environment:
      DATABASE_URL: "postgresql://docker:docker@db:5432/mynodeapi"
    depends_on:
      - db
  db:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mynodeapi
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
